# Generated by Django 4.0.8 on 2022-10-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_planted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('height', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to=None)),
                ('description', models.TextField()),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='planty.plant')),
            ],
        ),
    ]
