# Generated by Django 4.0.8 on 2022-11-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
