# Generated by Django 4.0.8 on 2022-12-07 21:49

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planty', '0003_plant_author_alter_event_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
